# Generated by Django 3.0.2 on 2020-09-10 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_createnewlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewlist',
            old_name='default',
            new_name='ended',
        ),
        migrations.AddField(
            model_name='createnewlist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
