# Generated by Django 3.0.2 on 2020-09-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200910_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewlist',
            old_name='bidder',
            new_name='owner',
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=64)),
                ('start_bid', models.IntegerField()),
                ('raise_bid', models.IntegerField(default=0)),
                ('owner', models.CharField(max_length=64)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_id', to='auctions.Createnewlist')),
            ],
        ),
    ]
