# Generated by Django 3.0.2 on 2020-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200911_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createnewlist',
            name='image_url',
        ),
        migrations.AddField(
            model_name='createnewlist',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
