# Generated by Django 3.0.2 on 2020-09-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_start_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='raise_bid',
            new_name='start_bid',
        ),
    ]
