# Generated by Django 3.0.2 on 2020-09-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200913_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='start_bid',
            new_name='raise_bid',
        ),
    ]
