# Generated by Django 3.0.2 on 2020-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200913_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_id', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('mywatchitems', models.ManyToManyField(blank=True, related_name='myitems', to='auctions.Createnewlist')),
            ],
        ),
    ]
