# Generated by Django 3.0.2 on 2020-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('commentator', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='mywatchitems',
        ),
    ]
