# Generated by Django 3.0.2 on 2020-09-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200914_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_item', models.IntegerField()),
                ('winnerp', models.CharField(max_length=64)),
                ('firsttime', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
