# Generated by Django 3.0.2 on 2020-09-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='firsttime',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
