# Generated by Django 3.0.5 on 2024-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200915_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
        migrations.RenameField(
            model_name='createnewlist',
            old_name='start_bid',
            new_name='id_value',
        ),
        migrations.RenameField(
            model_name='createnewlist',
            old_name='ended',
            new_name='prediction_dt',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='time',
        ),
        migrations.RemoveField(
            model_name='createnewlist',
            name='title',
        ),
        migrations.AddField(
            model_name='createnewlist',
            name='prediction_knn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='createnewlist',
            name='prediction_rf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='createnewlist',
            name='prediction_svm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
